version: "3"
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli
    networks:
      - backend
    ports:
      - "8545:8545"
  truffle:
    container_name: truffle
    build: ./truffle
    networks:
      - backend
    volumes:
      - ./truffle:/home/truffle-app
    depends_on:
      - ganache
networks:
  backend:
    driver: bridge
