version: "3.5"
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli
    networks:
      - backend
    ports:
      - "8545:8545"
  truffle:
    container_name: truffle
    build: ./
    networks:
      - backend
    volumes:
      - ./:/home/truffle-app
    depends_on:
      - ganache
networks:
  backend:
    name: blockchain_network
    driver: bridge
