version: "3"
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli
    networks:
      - backend
  truffle:
    container_name: truffle
    build: ./truffle
    networks:
      - backend
    volumes:
      - ./truffle-app:/home/truffle-app
networks:
  backend:
    driver: bridge
